name: "sprout & co's blog"
description: "dispatches from the future of learning"
url: http://thesprouts.org/blog

baseurl: /
source: ./
destination: ./_public
permalink: /blog/:title

asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  gzip: false